addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.11")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.1.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.29")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.6.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "3.7")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
